name: multi-node-hadoop

services:
  spark-yarn-master:
    build: 
      context: .
      dockerfile: Dockerfile
      additional_contexts:
        - downloads=/mnt/c/Users/temmyzeus/Downloads
    image: spark-yarn-image
    ports:
      - "9000:9000"
      - "9870:9870"
      - "8088:8088"
      - "7077:7077"
    entrypoint: [ "./entrypoint.sh", "master" ]
  spark-yarn-worker: # For the HDFS Datanode & Yarn  NodeManager
    image: spark-yarn-image
    entrypoint: [ "./entrypoint.sh", "worker" ]
    depends_on:
      - spark-yarn-master
  spark-history-server:
    image: spark-yarn-image
    entrypoint: [ "./entrypoint.sh", "history" ]
    depends_on:
      - spark-yarn-master
    ports:
      - "18080:18080"
